# usage: https://taskfile.dev/usage/
#
# Quorum Style: Please generally write tasks with the following naming convention:
#   verb[:OPT object][:OPT environment]
#   [start, stop, cleanup]:[backend, frontend, db]:[local, dev, prod, ci]
#       object is optional if the verb can only logically be done on one thing, e.g.
#           "debug" inherently only applies to the backend, so you don't need to specify
#
#   We also assume that, if an environment is not specified, the user means Local; we
#       do not need to specify local explicitly
#
#   Do not rigidly follow this style if it produces illogical or inconvenient results

version: 3

env:
  COMPOSE_FILE: docker-compose.yml

tasks:

  "build":
    desc: Install plum dependencies
    cmds:
      - docker compose run --rm plum npm install

  "test":
    desc: Run the test suite
    summary: |
      Run the test suite

      Running without arguments will run the entire suite.

      To run a specific frontend test / folder of tests / path of tests:
        task test -- some/path/to/__tests__/test.js
        task test -- some/path/to/__tests__/
        task test -- some/path/

      Separate multiple test files/folders/paths with a space:
        task test:frontend -- some/path/ some/other
    cmds:
      - docker compose run --rm plum npx jest {{.CLI_ARGS}}

  # -------- STORYBOOK -------
  "start:storybook":
    desc: Start Storybook in the background
    cmds:
      - task: "stop:storybook"
      - docker compose up -d storybook

  "stop:storybook":
    desc: Stop Storybook
    cmds:
      - docker compose stop storybook

  "up:storybook":
    desc: Start Storybook in the foreground
    cmds:
      - docker compose up storybook

  "log:storybook":
    desc: View logs for Storybook (similar to `tail --follow`)
    cmds:
      - docker compose logs storybook --follow
