import "@mantine/core/styles.css"

// This must be rendered in the root of the app (In addition to the v6 MantineProvider)
export { MantineProvider as PlumProvider } from "@mantine/core"

export { Alert } from "./components/Alert"
export { Button } from "./components/Button"
export { Checkbox } from "./components/Checkbox"
export { Dialog } from "./components/Dialog"
export { Highlight } from "./components/Highlight"
export { Label } from "./components/Label"
export { Menu } from "./components/Menu"
export { Modal } from "./components/Modal"
export { MultiSelect } from "./components/MultiSelect"
export { PageTitle } from "./components/PageTitle"
export { Radio } from "./components/Radio"
export { Select } from "./components/Select"
export { Tabs } from "./components/Tabs"
export { TextField } from "./components/TextField"
export { Tile } from "./components/Tile"
export { Tooltip } from "./components/Tooltip"
export { Switch } from "./components/Switch"
export { Avatar } from "./components/Avatar"
