import "@mantine/core/styles.css"

// This must be rendered in the root of the app (In addition to the v6 MantineProvider)
export { MantineProvider as PlumProvider } from "@mantine/core"

export { Alert } from "./components/Alert"
export { Badge } from "./components/Badge"
export { Button } from "./components/Button"
export { Checkbox } from "./components/Checkbox"
export { Label } from "./components/Label"
export { Menu } from "./components/Menu"
export { Modal } from "./components/Modal"
export { MultiSelect } from "./components/MultiSelect"
export { Radio } from "./components/Radio"
export { Select } from "./components/Select"
export { Tabs } from "./components/Tabs"
export { Stepper } from "./components/Stepper"
export { TextField } from "./components/TextField"
export { Tile } from "./components/Tile"
export { Tooltip } from "./components/Tooltip"
export { Switch } from "./components/Switch"
export { Avatar } from "./components/Avatar"
export { SegmentedControl } from "./components/SegmentedControl"
export { Table } from "./components/Table"
export { ProgressIndicator as Loader } from "./components/ProgressIndicator"
export { DatePicker } from "./components/DatePicker"
export { ColorPicker } from "./components/ColorPicker"
