name: Publish Plum to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: pnpm i
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
